Algoritmo "DesvioCondicional"
//Nome: Alexander Souza
// Data atual  : 22/12/2018
Var
// Seção de Declarações das variáveis 
   idade: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Informe sua idade: ")
   leia(idade)
   
   se(idade >= 18)entao
      escreva("Você é maior de idade, pode tirar carteira de motorista")
   senao
        escreva("Você não pode tirar carteira de motorista")
   fimse

Fimalgoritmo