Algoritmo "Tabuada"
//Alexander
// Data atual  : 25/12/2018
Var
// Seção de Declarações das variáveis
   tabuada: inteiro
   contador: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Escolha a tabuada que deseja: ")
   leia(tabuada)
   
   para contador de 1 ate 10 faca
        escreval(tabuada," x ", contador," = ",(tabuada*contador))
   fimpara
Fimalgoritmo